// resources/assets/react/components/passport/Clients.js
import React, { Component } from 'react';

class Clients extends Component { 
    constructor(props) { 
        super(props); 
 
        this.state = { 
            clients: [],
            client: [],
            scopes: [],
            form: {
                errors: [],
                name: '',
                asso_id: 1,
                redirect: '',
                scopes: []
            }
        } 
    }

    componentDidMount() {
        this.getClients();
        this.getTokens();
    }

    getClients() {
        axios.get('/oauth/clients').then(response => {
            var clients = response.data;

            clients.map(function(client) {
                try {
                    client.scopes = JSON.parse(client.scopes);

                    if (client.scopes === null) {
                        client.scopes = [];
                    }
                }
                catch (error) {
                    console.log(error);
                    client.scopes = [];
                }
            });

            this.setState({ clients: clients });
        });
    }

    getTokens() {
        axios.get('/oauth/scopes').then(response => {
            var scopes = [];

            Object.keys(response.data).forEach(function(key) {
                if (key.startsWith('client')) {
                    scopes.push({
                        'name': key,
                        'description': response.data[key]
                    });
                }
            });

            this.setState({ scopes: scopes });
        });
    }

    viewClient(client, e) {
        this.setState({ client: client });
        $("#viewModal").modal('toggle');
    }

    editClient(client, e) {
        this.setState({ client: client });
        $("#editModal").modal('toggle');
    }

    deleteClient(client, e) {
        axios.delete('/oauth/clients/' + this.state.client.id)
            .then(response => {
                this.getClients();
            });
    }

    handleInputChange(e) {
        const name = e.target.name;
        const value = e.target.value;  
        const oldForm = this.state.form;

        var form = {
            errors: oldForm.errors,
            name: oldForm.name,
            asso_id: oldForm.asso_id,
            redirect: oldForm.redirect,
            scopes: oldForm.scopes
        }

        if (name === "scope") {
            const i = form.scopes.indexOf(value);
            if (i == -1) {
                form.scopes.push(value);
            } else {
                form.scopes.splice(i, 1);
            }
        } else {
            form[name] = e.target.value;
        }

        this.setState({ form: form });
    }

    handleSubmit(method, url, e) {
        e.preventDefault();

        var form = this.state.form;
        form.errors = [];

        axios({ method: method, url: url, data: form })
            .then(response => {
                this.getClients();
                
                var form = {
                    errors: [],
                    name: '',
                    asso_id: '',
                    redirect: '',
                    scopes: []
                }

                this.setState({ form: form });

                $("#createModal").modal('toggle');
            })
            .catch(error => {                
                form.errors = ['Une erreur est survenue. Veuillez réessayer'];
                this.setState({ form: form });
            });
    }

    render() {
        return (
            <div>
                <div className="card drop-shadow mb-4">
                    <div className="card-body">
                        <div className="row">
                            <div className="col-6">
                                <h5><b>Clients OAuth</b></h5>
                            </div>

                            <div className="col-6 text-right">
                                <a className="btn btn-primary" href="#createModal" data-toggle="modal">Créer un client</a>
                            </div>
                        </div>

                        { this.state.clients.length > 0 ? (
                            this.state.clients.map((client, i) => 
                                <dl key={i} className="row mt-3 mb-0">
                                    <dt className="col-sm-3">
                                        <span className="d-block mb-2">{ client.name }</span> 
                                        <button className="btn btn-primary btn-sm mb-1 mr-1" onClick={ (e) => this.viewClient(client, e) }>
                                            Voir
                                        </button>
                                        <button className="btn btn-primary btn-sm mb-1" onClick={ (e) => this.editClient(client, e) }>
                                            Modifier
                                        </button>
                                    </dt>
                                    <dd className="col-sm-9">
                                        ID Client : { client.id } <br/>
                                        ID Asso : { client.asso_id } <br />
                                        Secret : <code>{ client.secret }</code> <br />
                                    </dd>
                                </dl>
                            )
                        ) : (
                            <p className="mt-3 mb-0">Vous n'avez pas encore crée de client OAuth.</p>
                        )}
                    </div>
                </div>

                <div className="modal fade" id="createModal" tabindex="-1" role="dialog">
                    <div className="modal-dialog modal-lg">
                        <div className="modal-content">
                            <div className="modal-body">
                                <div className="row mb-3">
                                    <div className="col-6">
                                        <h4><b>Créer un client</b></h4>
                                    </div>
                                    <div className="col-6 text-right">
                                        <button id="hideModalBtn" type="button" className="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                    </div>
                                </div>

                                { this.state.form.errors.length > 0 ? (
                                    <div className="alert alert-danger" v-if="form.errors.length > 0">
                                        <p className="mb-0"><strong>Erreur</strong></p>
                                        <br />
                                        Une erreur est survenue. Veuillez réessayer.
                                    </div>
                                ) : (<span></span>)}

                                <form onSubmit={ (e) => this.handleSubmit('post', 'oauth/clients', e) }>
                                    <div className="form-group row">
                                        <label className="col-md-3 col-form-label">Nom :</label>

                                        <div className="col-md-9">
                                            <input id="create-client-name" type="text" className="form-control" name="name" onChange={ (e) => this.handleInputChange(e) } />

                                            <span className="form-text text-muted">Le nom qui s'affichera pour vos utilisateurs.</span>
                                        </div>
                                    </div>

                                    <div className="form-group row">
                                        <label className="col-md-3 col-form-label">ID Asso :</label>

                                        <div className="col-md-9">
                                            <input name="asso_id" type="number" min="0" className="form-control" onChange={ (e) => this.handleInputChange(e) } />

                                            <span className="form-text text-muted">
                                                L'ID de l'asso pour qui la clé est créee.
                                            </span>
                                        </div>
                                    </div>

                                    <div className="form-group row">
                                        <label className="col-md-3 col-form-label">Redirection :</label>

                                        <div className="col-md-9">
                                            <input type="text" className="form-control" name="redirect" onChange={ (e) => this.handleInputChange(e) } />

                                            <span className="form-text text-muted">
                                                Adresse de redirection après authentification.
                                            </span>
                                        </div>
                                    </div>

                                    <div className="form-group row">
                                        <label className="col-md-3 col-form-label">Scopes :</label>

                                        <div className="col-md-9">
                                            { this.state.scopes.length > 0 ? (
                                                this.state.scopes.map((scope, i) =>
                                                    <div key={i} className="checkbox">
                                                        <label>
                                                            <input type="checkbox" name="scope" value={ scope.name } onChange={ (e) => this.handleInputChange(e) } />
                                                            &nbsp;
                                                            <span data-toggle="tooltip" data-placement="right" title={ scope.description }>{ scope.name }</span>
                                                        </label>
                                                    </div>
                                                )
                                            ) : (
                                                <span></span>
                                            )}
                                        </div>
                                    </div>

                                    <div className="row">
                                        <div className="col-6 text-left">
                                            <button type="button" className="btn btn-primary" data-dismiss="modal">Annuler</button>
                                        </div>
                                        <div className="col-6 text-right">
                                            <button type="submit" className="btn btn-primary">Créer le client</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>

                <div className="modal fade" id="viewModal" tabindex="-1" role="dialog">
                    <div className="modal-dialog modal-lg">
                        <div className="modal-content">
                            <div className="modal-body">
                                <div className="row mb-3">
                                    <div className="col-6">
                                        <h4><b>Voir</b></h4>
                                    </div>
                                    <div className="col-6 text-right">
                                        <button type="button" className="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                    </div>
                                </div>

                                <form role="form">
                                    <div className="form-group row">
                                        <label className="col-md-3 col-form-label">Nom :</label>

                                        <div className="col-md-9">
                                            <input type="text" disabled className="form-control" value={ this.state.client.name } />

                                            <span className="form-text text-muted">Le nom qui s'affichera pour vos utilisateurs.</span>
                                        </div>
                                    </div>

                                    <div className="form-group row">
                                        <label className="col-md-3 col-form-label">ID Asso :</label>

                                        <div className="col-md-9">
                                            <input type="number" min="0" disabled className="form-control" value={ this.state.client.asso_id } />

                                            <span className="form-text text-muted">L'ID de l'asso pour qui la clé est créee.</span>
                                        </div>
                                    </div>

                                    <div className="form-group row">
                                        <label className="col-md-3 col-form-label">Redirection :</label>

                                        <div className="col-md-9">
                                            <input type="text" className="form-control" disabled value={ this.state.client.redirect } />

                                            <span className="form-text text-muted">Adresse de redirection après authentification.</span>
                                        </div>
                                    </div>

                                    <div className="form-group row" v-if="form.scopes.length > 0">
                                        <label className="col-md-3 col-form-label">Scopes :</label>

                                        <div className="col-md-9">
                                        { this.state.client.scopes ? (
                                            this.state.client.scopes.map((scope, i) => 
                                                <span key={i} className="d-block mb-1">
                                                    <code>{ scope }</code> : scopes[scope]
                                                </span>
                                            )
                                        ) : (
                                            <span>Pas de scopes client.</span>
                                        )}
                                        </div>
                                    </div>
                                </form>

                                <div className="row">
                                    <div className="col-12 text-right">
                                        <button type="button" className="btn btn-primary" data-dismiss="modal">Fermer</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div className="modal fade" id="editModal" tabindex="-1" role="dialog">
                    <div className="modal-dialog modal-lg">
                        <div className="modal-content">
                            <div className="modal-body">
                                <div className="row mb-3">
                                    <div className="col-6">
                                        <h4><b>Modifier un client</b></h4>
                                    </div>
                                    <div className="col-6 text-right">
                                        <button type="button" className="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                    </div>
                                </div>

                                { this.state.form.errors.length > 0 ? (
                                    <div className="alert alert-danger" v-if="form.errors.length > 0">
                                        <p className="mb-0"><strong>Erreur</strong></p>
                                        <br />
                                        Une erreur est survenue. Veuillez réessayer.
                                    </div>
                                ) : (<span></span>)}

                                <form onSubmit={ (e) => this.handleSubmit('post', 'oauth/clients', e) }>
                                    <div className="form-group row">
                                        <label className="col-md-3 col-form-label">Nom :</label>

                                        <div className="col-md-9">
                                            <input id="create-client-name" type="text" className="form-control" name="name" value={ this.state.client.name } onChange={ (e) => this.handleInputChange(e) } />

                                            <span className="form-text text-muted">Le nom qui s'affichera pour vos utilisateurs.</span>
                                        </div>
                                    </div>

                                    <div className="form-group row">
                                        <label className="col-md-3 col-form-label">ID Asso :</label>

                                        <div className="col-md-9">
                                            <input name="asso_id" type="number" min="0" className="form-control" value={ this.state.client.asso_id } onChange={ (e) => this.handleInputChange(e) } />

                                            <span className="form-text text-muted">
                                                L'ID de l'asso pour qui la clé est créee.
                                            </span>
                                        </div>
                                    </div>

                                    <div className="form-group row">
                                        <label className="col-md-3 col-form-label">Redirection :</label>

                                        <div className="col-md-9">
                                            <input type="text" className="form-control" name="redirect" value={ this.state.client.redirect } onChange={ (e) => this.handleInputChange(e) } />

                                            <span className="form-text text-muted">
                                                Adresse de redirection après authentification.
                                            </span>
                                        </div>
                                    </div>

                                    <div className="form-group row">
                                        <label className="col-md-3 col-form-label">Scopes :</label>

                                        <div className="col-md-9">
                                            { this.state.scopes.length > 0 ? (
                                                this.state.scopes.map((scope, i) => {
                                                    var isChecked = false;
                                                    if (this.state.client.scopes && this.state.client.scopes.indexOf(scope.name) != -1) 
                                                        isChecked = true;

                                                    return <div key={i} className="checkbox">
                                                        <label>
                                                            <input type="checkbox" name="scope" value={ scope.name } onChange={ (e) => this.handleInputChange(e) } checked={ isChecked ? "checked" : false } />
                                                            &nbsp;
                                                            <span data-toggle="tooltip" data-placement="right" title={ scope.description }>{ scope.name }</span>
                                                        </label>
                                                    </div>
                                                })
                                            ) : (
                                                <span></span>
                                            )}
                                        </div>
                                    </div>

                                    <div className="row">
                                        <div className="col-6 text-left">
                                            <button type="button" className="btn btn-primary" data-dismiss="modal">Annuler</button>
                                        </div>
                                        <div className="col-6 text-right">
                                            <button type="button" className="btn btn-danger mr-2" data-dismiss="modal" onClick={ (e) => this.deleteClient(this.state.client, e) }>Supprimer</button>
                                            <button type="submit" className="btn btn-primary">Modifier le client</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        );
    }
}

export default Clients;

// resources/assets/js/components/passport/Clients.vue
<template>
    <div>
        <div class="card drop-shadow mb-4">
            <div class="card-body">
                <div class="row">
                    <div class="col-6">
                        <h5><b>Clients OAuth</b></h5>
                    </div>

                    <div class="col-6 text-right">
                        <a class="btn btn-primary" tabindex="-1" @click="showCreateClientForm">Créer un client</a>
                    </div>
                </div>

                <p class="mt-3 mb-0" v-if="clients.length === 0">Vous n'avez pas encore crée de client OAuth.</p>

                <!-- OAuth Clients -->
                <dl class="row mt-3 mb-0" v-if="clients.length > 0" v-for="client in clients">
                    <dt class="col-sm-3">
                        <span class="d-block mb-2">{{ client.name }}</span> 
                        <button class="btn btn-primary btn-sm mb-1" tabindex="-1" @click="see(client)">
                            Voir
                        </button>
                        <button class="btn btn-primary btn-sm mb-1" tabindex="-1" @click="edit(client)">
                            Modifier
                        </button>
                    </dt>
                    <dd class="col-sm-9">
                        ID Client : {{ client.id }} <br/>
                        ID Asso : {{ client.asso_id }} <br />
                        Secret : <code>{{ client.secret }}</code> <br />
                    </dd>
                </dl>
            </div>
        </div>

        <!-- Create Client Modal -->
        <div class="modal fade" id="modal-create-client" tabindex="-1" role="dialog">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <div class="modal-body">
                        <div class="row mb-3">
                            <div class="col-6">
                                <h4><b>Créer un client</b></h4>
                            </div>
                            <div class="col-6 text-right">
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                            </div>
                        </div>

                        <!-- Form Errors -->
                        <div class="alert alert-danger" v-if="form.errors.length > 0">
                            <p class="mb-0"><strong>Erreur</strong></p>
                            <br>
                            <ul>
                                <li v-for="error in form.errors">
                                    {{ error }}
                                </li>
                            </ul>
                        </div>

                        <!-- Create Client Form -->
                        <form role="form">
                            <!-- Name -->
                            <div class="form-group row">
                                <label class="col-md-3 col-form-label">Nom :</label>

                                <div class="col-md-9">
                                    <input id="create-client-name" type="text" class="form-control" @keyup.enter="store" v-model="form.name">

                                    <span class="form-text text-muted">Le nom qui s'affichera pour vos utilisateurs.</span>
                                </div>
                            </div>

                            <!-- Asso -->
                            <div class="form-group row">
                                <label class="col-md-3 col-form-label">ID Asso :</label>

                                <div class="col-md-9">
                                    <input name="asso_id" type="number" min="0" class="form-control" @keyup.enter="store" v-model="form.asso_id">

                                    <span class="form-text text-muted">
										L'ID de l'asso pour qui la clé est créee.
                                    </span>
                                </div>
                            </div>

                            <!-- Redirect URL -->
                            <div class="form-group row">
                                <label class="col-md-3 col-form-label">Redirection :</label>

                                <div class="col-md-9">
                                    <input type="text" class="form-control" name="redirect" value="http://example.com" @keyup.enter="store" v-model="form.redirect">

                                    <span class="form-text text-muted">
                                        Adresse de redirection après authentification.
                                    </span>
                                </div>
                            </div>

                            <!-- Scopes -->
                            <div class="form-group row">
                                <label class="col-md-3 col-form-label">Scopes :</label>

								<div class="col-md-9">
                                    <div v-for="(description, name) in scopes" v-if="name.startsWith('client')">
                                        <div class="checkbox">
                                            <label>
                                                <input type="checkbox"
                                                    @click="toggleScope(name)"
                                                    :checked="scopeIsAssigned(name)">

                                                &nbsp;

                                                <span data-toggle="tooltip" data-placement="right" :title="description">{{ name }}</span>
                                            </label>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>

                        <!-- Modal Actions -->
                        <div class="row">
                            <div class="col-6 text-left">
                                <button type="button" class="btn btn-primary" data-dismiss="modal">Annuler</button>
                            </div>
                            <div class="col-6 text-right">
                                <button type="button" class="btn btn-primary" @click="store">Créer le client</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- View Client Modal -->
        <div class="modal fade" id="modal-see-client" tabindex="-1" role="dialog">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <div class="modal-body">
                        <div class="row mb-3">
                            <div class="col-6">
                                <h4><b>Voir</b></h4>
                            </div>
                            <div class="col-6 text-right">
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                            </div>
                        </div>

                        <!-- Edit Client Form -->
                        <form role="form">
                            <!-- Name -->
                            <div class="form-group row">
                                <label class="col-md-3 col-form-label">Nom :</label>

                                <div class="col-md-9">
                                    <input id="edit-client-name" type="text" disabled class="form-control"
                                                                @keyup.enter="update" v-model="form.name">

                                    <span class="form-text text-muted">Le nom qui s'affichera pour vos utilisateurs.</span>
                                </div>
                            </div>

                            <!-- Asso -->
                            <div class="form-group row">
                                <label class="col-md-3 col-form-label">ID Asso :</label>

                                <div class="col-md-9">
                                    <input type="number" min="0" disabled class="form-control"
                                                                @keyup.enter="update" v-model="form.asso_id">

                                    <span class="form-text text-muted">L'ID de l'asso pour qui la clé est créee.</span>
                                </div>
                            </div>

                            <!-- Redirect URL -->
                            <div class="form-group row">
                                <label class="col-md-3 col-form-label">Redirection :</label>

                                <div class="col-md-9">
                                    <input type="text" class="form-control" disabled name="redirect"
                                                    @keyup.enter="update" v-model="form.redirect">

                                    <span class="form-text text-muted">Adresse de redirection après authentification.</span>
                                </div>
                            </div>

							<!-- Scopes -->
                            <div class="form-group row" v-if="form.scopes.length > 0" @keyup.enter="update" v-model="form.scopes">
                                <label class="col-md-3 col-form-label">Scopes :</label>

                                <div class="col-md-9">
                                    <span class="d-block mb-1" v-for="scope in form.scopes">
                                        <code>{{ scope }}</code> : {{ scopes[scope] }}
                                    </span>
                                </div>
                            </div>
                        </form>

                        <div class="row">
                            <div class="col-12 text-right">
                                <button type="button" class="btn btn-primary" data-dismiss="modal">Fermer</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Edit Client Modal -->
        <div class="modal fade" id="modal-edit-client" tabindex="-1" role="dialog">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <div class="modal-body">
                        <div class="row mb-3">
                            <div class="col-6">
                                <h4><b>Modifier un client</b></h4>
                            </div>
                            <div class="col-6 text-right">
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                            </div>
                        </div>

                        <!-- Form Errors -->
                        <div class="alert alert-danger" v-if="form.errors.length > 0">
                            <p class="mb-0"><strong>Erreur</strong></p>
                            <br>
                            <ul>
                                <li v-for="error in form.errors">
                                    {{ error }}
                                </li>
                            </ul>
                        </div>

                        <!-- Edit Client Form -->
                        <form role="form">
                            <!-- Name -->
                            <div class="form-group row">
                                <label class="col-md-3 col-form-label">Nom :</label>

                                <div class="col-md-9">
                                    <input id="edit-client-name" type="text" class="form-control"
                                                                @keyup.enter="update" v-model="form.name">

                                    <span class="form-text text-muted">Le nom qui s'affichera pour vos utilisateurs.</span>
                                </div>
                            </div>

                            <!-- Redirect URL -->
                            <div class="form-group row">
                                <label class="col-md-3 col-form-label">Redirection :</label>

                                <div class="col-md-9">
                                    <input type="text" class="form-control" name="redirect"
                                                    @keyup.enter="update" v-model="form.redirect">

                                    <span class="form-text text-muted">Adresse de redirection après authentification.</span>
                                </div>
                            </div>

							<!-- Scopes -->
                            <div class="form-group row">
                                <label class="col-md-3 col-form-label">Scopes :</label>

								<div class="col-md-9">
                                    <div v-for="(description, name) in scopes" v-if="name.startsWith('client')">
                                        <div class="checkbox">
                                            <label>
                                                <input type="checkbox"
                                                    @click="toggleScope(name)"
                                                    :checked="scopeIsAssigned(name)">

                                                    &nbsp;

                                                    <span data-toggle="tooltip" data-placement="right" :title="description">{{ name }}</span>
                                            </label>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>

                        <!-- Modal Actions -->
                        <div class="row">
                            <div class="col-6 text-left">
                                <button type="button" class="btn btn-primary" data-dismiss="modal">Annuler</button>
                            </div>
                            <div class="col-6 text-right">
                                <button type="button" class="btn btn-danger mr-2" data-dismiss="modal" @click="destroy">Supprimer</button>
                                <button type="button" class="btn btn-primary" @click="store">Modifier le client</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

<script>
    export default {
        /*
         * The component's data.
         */
        data() {
            return {
                clients: [],
				client: {},

				scopes: [],

                form: {
                    errors: [],
					name: '',
                    asso_id: 1,
                    redirect: '',
					scopes: []
                },
            };
        },

        /**
         * Prepare the component (Vue 1.x).
         */
        ready() {
            this.prepareComponent();
        },

        /**
         * Prepare the component (Vue 2.x).
         */
        mounted() {
            this.prepareComponent();
        },

        methods: {
            /**
             * Prepare the component.
             */
            prepareComponent() {
                this.getClients();
				this.getScopes();

                $('#modal-create-client').on('shown.bs.modal', () => {
                    $('#create-client-name').focus();
                });

                $('#modal-edit-client').on('shown.bs.modal', () => {
                    $('#edit-client-name').focus();
                });
            },

            /**
             * Get all of the OAuth clients for the user.
             */
            getClients() {
                axios.get('/oauth/clients')
                        .then(response => {
                            this.clients = response.data;
                        });
            },

			/**
			 * Get all of the available scopes.
			 */
			getScopes() {
				axios.get('/oauth/scopes')
						.then(response => {
							this.scopes = response.data;
						});
			},

            /**
             * Toggle the given scope in the list of assigned scopes.
             */
            toggleScope(scope) {
                if (this.scopeIsAssigned(scope)) {
                    this.form.scopes = _.reject(this.form.scopes, s => s == scope);
                } else {
                    this.form.scopes.push(scope);
                }
            },

            /**
             * Determine if the given scope has been assigned to the token.
             */
            scopeIsAssigned(scope) {
                return _.indexOf(this.form.scopes, scope) >= 0;
            },

            /**
             * Show the form for creating new clients.
             */
            showCreateClientForm() {
				this.form = {
                    errors: [],
					name: '',
                    asso_id: 1,
                    redirect: '',
					scopes: []
                };

                $('#modal-create-client').modal('show');
            },

            /**
             * Create a new OAuth client for the user.
             */
            store() {
                this.persistClient(
                    'post', '/oauth/clients',
                    this.form, '#modal-create-client'
                );
            },

            /**
             * See the given client.
             */
            see(client) {
                this.form.id = client.id;
				this.form.name = client.name;
                this.form.asso_id = client.asso_id;
				this.form.redirect = client.redirect;

				try {
					this.form.scopes = JSON.parse(client.scopes);

					if (this.form.scopes === null)
						this.form.scopes = [];
				}
				catch (error) {
					this.form.scopes = [];
				}

                $('#modal-see-client').modal('show');
            },

            /**
             * Edit the given client.
             */
            edit(client) {
				this.client = client;
                this.form.id = client.id;
				this.form.name = client.name;
                this.form.asso_id = client.asso_id;
				this.form.redirect = client.redirect;

				try{
					this.form.scopes = JSON.parse(client.scopes);

					if (this.form.scopes === null)
						this.form.scopes = [];
				}
				catch (error){
					this.form.scopes = [];
				}

                $('#modal-edit-client').modal('show');
            },

            /**
             * Update the client being edited.
             */
            update() {
                this.persistClient(
                    'put', '/oauth/clients/' + this.form.id,
                    this.form, '#modal-edit-client'
                );
            },

            /**
             * Persist the client to storage using the given form.
             */
            persistClient(method, uri, form, modal) {
                form.errors = [];

                axios[method](uri, form)
                    .then(response => {
                        this.getClients();

                        form.name = '';
                        form.redirect = '';
                        form.errors = [];

                        $(modal).modal('hide');
                    })
                    .catch(error => {
                        if (typeof error.response.data === 'object') {
                            form.errors = _.flatten(_.toArray(error.response.data.errors));
                        } else {
                            form.errors = ['Une erreur est survenue. Veuillez réessayer'];
                        }
                    });
            },

            /**
             * Destroy the given client.
             */
            destroy() {
                axios.delete('/oauth/clients/' + this.client.id)
                        .then(response => {
                            this.getClients();
                        });
            }
        }
    }
</script>
